### PR TITLE
Turn off all commenting in a dumb way

### PR DESCRIPTION
**Pull request by andrusha**
Because it they are littering github PRs

### CODE REVIEW

**Comment by p0deje** [comment]
What about features? It will be messy and features vs. specs fight since we only have a single commit status.

**Comment by andrusha** [comment]
Is there a way to know from what's running? Maybe ENV variable or something?

**Comment by p0deje** [comment]
That's super hacky, but yes - https://jenkins.toptal.net/env-vars.html

**Comment by p0deje** [comment]
Don't you want to just implement multiple statuses support :wink:

**Comment by andrusha** [comment]
I just want to make it stop littering our history as soon as I can :)

**Comment by andrusha** [comment]
Too lazy to do it

**Pull request closed without merging**
